// Les textes de la recherche des clientes, dans la langue de SON navigateur :
// ici on ne connaît pas encore de pro, donc pas encore sa langue à elle.
// Fichier sans rien de serveur : les composants du navigateur l'importent.
export type Langue = 'fr' | 'en' | 'es'
export type Metier = 'ongles' | 'cils' | 'sourcils' | 'coiffure' | 'epilation' | 'maquillage' | 'soins'

export const TEXTES = {
  fr: {
    titre: 'Trouve ta pro beauté',
    sousTitre: 'Les professionnelles Glamia près de chez toi. Réserve en ligne, en quelques secondes.',
    villePlaceholder: 'Ta ville',
    autour: 'Autour de moi',
    localisation: 'Localisation…',
    localisationRefusee: 'Autorise la localisation dans ton navigateur, ou choisis ta ville.',
    pros: (n: number) => (n === 0 ? 'Aucune pro pour le moment' : n === 1 ? '1 pro' : `${n} pros`),
    autourTitre: 'Autour de toi',
    tout: 'Tout',
    dispo: 'Dispo',
    aujourdhui: "aujourd'hui",
    demain: 'demain',
    pasDeDispo: 'Pas de créneau ce mois-ci',
    carte: 'Carte',
    liste: 'Liste',
    changerVille: 'Changer de ville',
    videTitre: 'Pas encore de pro ici',
    videTexte: 'Essaie une ville voisine, ou autour de toi.',
    avis: (n: number) => `${n} avis`,
    locale: 'fr-FR',
    metiers: { ongles: 'Ongles', cils: 'Cils', sourcils: 'Sourcils', coiffure: 'Coiffure', epilation: 'Épilation', maquillage: 'Maquillage', soins: 'Soins' } as Record<Metier, string>,
  },
  en: {
    titre: 'Find your beauty pro',
    sousTitre: 'Glamia professionals near you. Book online in seconds.',
    villePlaceholder: 'Your city',
    autour: 'Near me',
    localisation: 'Locating…',
    localisationRefusee: 'Allow location in your browser, or choose your city.',
    pros: (n: number) => (n === 0 ? 'No pros yet' : n === 1 ? '1 pro' : `${n} pros`),
    autourTitre: 'Near you',
    tout: 'All',
    dispo: 'Free',
    aujourdhui: 'today',
    demain: 'tomorrow',
    pasDeDispo: 'No slot this month',
    carte: 'Map',
    liste: 'List',
    changerVille: 'Change city',
    videTitre: 'No pros here yet',
    videTexte: 'Try a nearby city, or near you.',
    avis: (n: number) => `${n} review${n > 1 ? 's' : ''}`,
    locale: 'en-GB',
    metiers: { ongles: 'Nails', cils: 'Lashes', sourcils: 'Brows', coiffure: 'Hair', epilation: 'Waxing', maquillage: 'Make-up', soins: 'Treatments' } as Record<Metier, string>,
  },
  es: {
    titre: 'Encuentra tu profesional de belleza',
    sousTitre: 'Las profesionales Glamia cerca de ti. Reserva online en segundos.',
    villePlaceholder: 'Tu ciudad',
    autour: 'Cerca de mí',
    localisation: 'Localizando…',
    localisationRefusee: 'Permite la ubicación en tu navegador, o elige tu ciudad.',
    pros: (n: number) => (n === 0 ? 'Aún no hay profesionales' : n === 1 ? '1 profesional' : `${n} profesionales`),
    autourTitre: 'Cerca de ti',
    tout: 'Todo',
    dispo: 'Libre',
    aujourdhui: 'hoy',
    demain: 'mañana',
    pasDeDispo: 'Sin huecos este mes',
    carte: 'Mapa',
    liste: 'Lista',
    changerVille: 'Cambiar de ciudad',
    videTitre: 'Aún no hay profesionales aquí',
    videTexte: 'Prueba una ciudad cercana, o cerca de ti.',
    avis: (n: number) => `${n} reseña${n > 1 ? 's' : ''}`,
    locale: 'es-ES',
    metiers: { ongles: 'Uñas', cils: 'Pestañas', sourcils: 'Cejas', coiffure: 'Peluquería', epilation: 'Depilación', maquillage: 'Maquillaje', soins: 'Tratamientos' } as Record<Metier, string>,
  },
} as const
export type Textes = (typeof TEXTES)[Langue]
