// Les textes de la recherche des clientes, dans la langue de SON navigateur :
// ici on ne connaît pas encore de pro, donc pas encore sa langue à elle.
// Fichier sans rien de serveur : les composants du navigateur l'importent.
export type Langue = 'fr' | 'en' | 'es'
// Les spécialités du catalogue de l'app, sous leurs noms à elles (pas « Ongles » :
// Manucure et Pédicure sont deux spécialités). « Autre » n'est pas un filtre.
export type Metier = 'manucure' | 'pedicure' | 'cils' | 'sourcils' | 'coiffure' | 'epilation' | 'soinVisage'
  | 'maquillage' | 'maquillageSemi' | 'massage' | 'soinDentaire' | 'bronzage'

export const TEXTES = {
  fr: {
    titre: 'Trouve ta pro beauté',
    titreChute: '',
    surtitre: 'Réservation en ligne',
    villeTitre: 'Pros beauté à',
    sousTitre: 'Et réserve en ligne, en quelques secondes.',
    proQuestion: 'Tu es une pro ?',
    proBandeau: 'Ton agenda et ta page de réservation, dans une app.',
    proBouton: 'Découvrir Glamia',
    villePlaceholder: 'Ville, code postal ou adresse',
    autour: 'Autour de moi',
    localisation: 'Localisation…',
    localisationRefusee: 'Autorise la localisation dans ton navigateur, ou choisis ta ville.',
    pros: (n: number) => (n === 0 ? 'Aucune pro pour le moment' : n === 1 ? '1 pro' : `${n} pros`),
    autourTitre: 'Autour de',
    autourChute: 'toi',
    tout: 'Tout',
    dispo: 'Dispo',
    aujourdhui: "aujourd'hui",
    demain: 'demain',
    pasDeDispo: 'Pas de créneau ce mois-ci',
    carte: 'Carte',
    liste: 'Liste',
    changerVille: 'Changer de ville',
    videTitre: 'Pas encore de pro ici',
    videTexte: 'Essaie une ville voisine, ou autour de toi.',
    avis: (n: number) => `${n} avis`,
    locale: 'fr-FR',
    metiers: { manucure: 'Manucure', pedicure: 'Pédicure', cils: 'Cils', sourcils: 'Sourcils', coiffure: 'Coiffure', epilation: 'Épilation', soinVisage: 'Soin visage', maquillage: 'Maquillage', maquillageSemi: 'Maquillage semi-permanent', massage: 'Massage', soinDentaire: 'Soin dentaire', bronzage: 'Bronzage' } as Record<Metier, string>,
  },
  en: {
    titre: 'Find your beauty pro',
    titreChute: '',
    surtitre: 'Online booking',
    villeTitre: 'Beauty pros in',
    sousTitre: 'And book online in seconds.',
    proQuestion: 'Are you a pro?',
    proBandeau: 'Your calendar and booking page, in one app.',
    proBouton: 'Discover Glamia',
    villePlaceholder: 'City, postcode or address',
    autour: 'Near me',
    localisation: 'Locating…',
    localisationRefusee: 'Allow location in your browser, or choose your city.',
    pros: (n: number) => (n === 0 ? 'No pros yet' : n === 1 ? '1 pro' : `${n} pros`),
    autourTitre: 'Near',
    autourChute: 'you',
    tout: 'All',
    dispo: 'Free',
    aujourdhui: 'today',
    demain: 'tomorrow',
    pasDeDispo: 'No slot this month',
    carte: 'Map',
    liste: 'List',
    changerVille: 'Change city',
    videTitre: 'No pros here yet',
    videTexte: 'Try a nearby city, or near you.',
    avis: (n: number) => `${n} review${n > 1 ? 's' : ''}`,
    locale: 'en-GB',
    metiers: { manucure: 'Manicure', pedicure: 'Pedicure', cils: 'Lashes', sourcils: 'Brows', coiffure: 'Hair', epilation: 'Waxing', soinVisage: 'Facials', maquillage: 'Make-up', maquillageSemi: 'Semi-permanent make-up', massage: 'Massage', soinDentaire: 'Teeth', bronzage: 'Tanning' } as Record<Metier, string>,
  },
  es: {
    titre: 'Encuentra tu profesional de belleza',
    titreChute: '',
    surtitre: 'Reserva online',
    villeTitre: 'Profesionales en',
    sousTitre: 'Y reserva online en segundos.',
    proQuestion: '¿Eres profesional?',
    proBandeau: 'Tu agenda y tu página de reservas, en una app.',
    proBouton: 'Descubrir Glamia',
    villePlaceholder: 'Ciudad, código postal o dirección',
    autour: 'Cerca de mí',
    localisation: 'Localizando…',
    localisationRefusee: 'Permite la ubicación en tu navegador, o elige tu ciudad.',
    pros: (n: number) => (n === 0 ? 'Aún no hay profesionales' : n === 1 ? '1 profesional' : `${n} profesionales`),
    autourTitre: 'Cerca de',
    autourChute: 'ti',
    tout: 'Todo',
    dispo: 'Libre',
    aujourdhui: 'hoy',
    demain: 'mañana',
    pasDeDispo: 'Sin huecos este mes',
    carte: 'Mapa',
    liste: 'Lista',
    changerVille: 'Cambiar de ciudad',
    videTitre: 'Aún no hay profesionales aquí',
    videTexte: 'Prueba una ciudad cercana, o cerca de ti.',
    avis: (n: number) => `${n} reseña${n > 1 ? 's' : ''}`,
    locale: 'es-ES',
    metiers: { manucure: 'Manicura', pedicure: 'Pedicura', cils: 'Pestañas', sourcils: 'Cejas', coiffure: 'Peluquería', epilation: 'Depilación', soinVisage: 'Tratamientos faciales', maquillage: 'Maquillaje', maquillageSemi: 'Micropigmentación', massage: 'Masaje', soinDentaire: 'Estética dental', bronzage: 'Bronceado' } as Record<Metier, string>,
  },
} as const
export type Textes = (typeof TEXTES)[Langue]
